spring:
  application:
    name: backoffice
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
        trace: false
  jpa:
    generate-ddl: true
    show-sql: true

logging:
  level:
    com.exam: debug
    org.springframework: info
    org.springframework.web: debug
    org.springframework.core.codec: debug
