spring:
  application:
    name: backoffice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lecture
    username: root
    password: 12345
  jpa:
    generate-ddl: false
    show-sql: true
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#      settings:
#        web-allow-others: false
#        trace: false

logging:
  level:
    com.exam: debug
    org.springframework: info
    org.springframework.web: debug
    org.springframework.core.codec: debug
