spring:
  application:
    name: backoffice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lecture
    username: root
    password: 12345
  jpa:
    generate-ddl: false
    show-sql: true

logging:
  level:
    com.exam: info
    org.springframework: info
    org.springframework.web: info
