spring:
  application:
    name: front
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lecture
    username: root
    password: 12345
  jpa:
    generate-ddl: false
  redis:
    host: 127.0.0.1
    port: 6379

logging:
  level:
    com.exam: debug
    org.springframework: info
    org.springframework.web: debug
    org.springframework.core.codec: debug
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
